<a href="https://colab.research.google.com/github/gyaneshhere/ReInforcementLearning/blob/main/examples/VLM_GRPO_basic_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example code for VLMGRPOTrainer

Please note that this notebook is intended only as a proof of concept using a simplified dataset. Do not expect meaningful results from this demonstration. Before deploying for your specific use case, you may fine-tune the model on your target data. For proper GRPO training methodology, please refer to the official Unsloth notebooks.

In [ ]:
!pip install --no-deps -U transformers==4.54.1
!pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124
!pip install --no-deps -U bitsandbytes accelerate xformers==0.0.29.post3 peft trl==0.18.2 cut_cross_entropy unsloth_zoo==2025.7.11
!pip install sentencepiece protobuf datasets huggingface_hub hf_transfer
!pip install --no-deps -U unsloth==2025.7.11
!pip install -U triton==3.2.0
!pip install --force-reinstall --no-deps git+https://github.com/GAD-cell/vlm-grpo.git@main

In [ ]:
import vlmgrpo
from unsloth import FastVisionModel # FastLanguageModel for LLMs

model, tokenizer = FastVisionModel.from_pretrained(
    "unsloth/Qwen2.5-VL-7B-Instruct",
    load_in_4bit = True, # Use 4bit to reduce memory use. False for 16bit LoRA.
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for long context
)

In [ ]:
model = FastVisionModel.get_peft_model(
    model,
    finetune_vision_layers     = True, # False if not finetuning vision layers
    finetune_language_layers   = True, # False if not finetuning language layers
    finetune_attention_modules = True, # False if not finetuning attention layers
    finetune_mlp_modules       = True, # False if not finetuning MLP layers

    r = 16,           # The larger, the higher the accuracy, but might overfit
    lora_alpha = 16,  # Recommended alpha == r at least
    lora_dropout = 0.1,
    bias = "none",
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
    # target_modules = "all-linear", # Optional now! Can specify a list if needed
)

In [ ]:
from datasets import load_dataset, Dataset

ds = load_dataset("AI4Math/MathVista",split="testmini")

def is_numeric_answer(example):
  try:
    float(example["answer"])
    return True
  except:
    return False

numeric_ds = ds.filter(is_numeric_answer) # For convenience and easier reward function definition, we keep only the float answer ex : 42

In [ ]:
print(numeric_ds)

Dataset({
    features: ['pid', 'question', 'image', 'decoded_image', 'choices', 'unit', 'precision', 'answer', 'question_type', 'answer_type', 'metadata', 'query'],
    num_rows: 566
})

# Data loader and reward functions

In [ ]:
reasoning_start = "<think>"
reasoning_end   = "</think>"
solution_start  = "<answer>"
solution_end    = "</answer>"

def format_fn(sample):
    image = sample['decoded_image']
    prompt = sample['question']
    answer = sample['answer']
    format = {"prompt": [
                  {
                  "role": "user",
                  "content": [
                      {"type": "image"}, # because we have only 1 image per sample
                      {"type": "text",  "text": f"{prompt} provide your reasoning between {reasoning_start} and {reasoning_end} and then your final answer between {solution_start} and (put a float here) {solution_end}"}]
                  }],
                  "image": [image.resize((512,512))],
                  "answer":answer,
              }
    return format

class FormattedDataset():
    def __init__(self, dataset, format_fn):
        self.dataset = dataset
        self.format_fn = format_fn

    def __getitem__(self, idx):
        item = self.dataset[idx]
        return self.format_fn(item)

    def __len__(self):
        return len(self.dataset)


train_dataset=FormattedDataset(dataset=numeric_ds,format_fn=format_fn)

In [ ]:
# Reward functions
def formatting_reward_func(completions,**kwargs):
    import re
    print("test")
    thinking_pattern = f'{reasoning_start}(.*?){reasoning_end}'
    answer_pattern = f'{solution_start}(.*?){solution_end}'

    scores=[]
    for completion in completions :
      score=0
      thinking_matches = re.findall(thinking_pattern, completion[0]['content'], re.DOTALL)
      answer_matches = re.findall(answer_pattern, completion[0]['content'], re.DOTALL)
      if len(thinking_matches) == 1 :
        score +=1.0
      if len(answer_matches) == 1 :
        score +=1.0
      scores.append(score)
    return scores


def correctness_reward_func(prompts, completions, answer, **kwargs) -> list[float]:
    import re

    answer_pattern = f'{solution_start}(.*?){solution_end}'

    responses = [re.findall(answer_pattern, completion[0]['content'], re.DOTALL) for completion in completions]
    q = prompts[0][-1]['content']

    print('-'*20, f"Question:\n{q}", f"\nAnswer:\n{answer[0]}", f"\nResponse:{completions[0]}")
    return [2.0 if len(r)==1 and a == r[0].replace('\n','') else 0.0 for r, a in zip(responses, answer)]

# pour contrer le design du GRPO
#def length_reward_func(prompts, completions, answer, **kwargs):

# GRPO Training

In [ ]:
from unsloth import is_bf16_supported
from vlmgrpo import VLMGRPOTrainer
from trl import GRPOConfig

training_args = GRPOConfig(
    learning_rate = 5e-6,
    adam_beta1 = 0.9,
    adam_beta2 = 0.99,
    weight_decay = 0.1,
    warmup_ratio = 0.1,
    lr_scheduler_type = "cosine",
    optim = "adamw_8bit",
    logging_steps = 1,
    bf16 = is_bf16_supported(),
    fp16 = not is_bf16_supported(),
    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 2, # Decrease if out of memory
    max_prompt_length = 256,
    max_completion_length = 200,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 250,
    save_steps = 250,
    max_grad_norm = 0.1,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",
)

trainer = VLMGRPOTrainer(
    model = model,
    processing_class=tokenizer, # MUST put unsloth processor here !
    reward_processing_classes = tokenizer, #Here also
    reward_funcs = [
        formatting_reward_func,
        correctness_reward_func,
    ],
    args = training_args,
    train_dataset = train_dataset,
    grad_verbose=True
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 566 | Num Epochs = 1 | Total steps = 250
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 1 x 1) = 2
 "-____-"     Trainable parameters = 51,521,536 of 8,343,688,192 (0.62% trained)
`generation_config` default values have been modified to match model-specific defaults: {'max_length': 32768, 'temperature': 1e-06, 'repetition_penalty': 1.05, 'bos_token_id': 151643}. If this is not desired, please set these values explicitly.

Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the highest value on the X axis? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
30
Response:[{'role': 'assistant', 'content': 'What is the highest value on the X axis? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe X-axis in the graph represents "MICROGRAMS/mL-E-DNP-LYSINE-HCL". The values on the X-axis range from 0 to 30, with increments of 5. The highest value on the X-axis is therefore 30.\n</think>\n<answer>\n30.0\n</answer>'}]

`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...

[DEBUG] Loss: 2.0194531202832877e-07
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 60.0924

Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
6
Response:[{'role': 'assistant', 'content': "What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe image shows two individuals standing next to each other, but without knowing their exact ages or having additional context, it's impossible to determine the precise age gap between them. The individuals appear to be young adults, possibly in their late teens or early twenties, based on their physical appearance and attire. However, this is just an educated guess and not a definitive statement.\n</think>\n<answer>\n(0.5)\n</answer>"}]
Unsloth: Will smartly offload gradients to save VRAM!
[DEBUG] Loss: 1.3184548208755587e-07
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 403.4322
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'Subtract all yellow metallic balls. Subtract all small yellow shiny things. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
8
Response:[{'role': 'assistant', 'content': "Subtract all yellow metallic balls. Subtract all small yellow shiny things. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo solve this, let's identify the objects in the image:\n\n1. There is one yellow metallic ball.\n2. There are two small yellow shiny cylinders.\n\nWe need to subtract these objects from the total count of objects in the image.\n\nThe total number of objects in the image is 10:\n- 1 large blue cube\n- 1 small blue cube\n- 1 small blue metallic cube\n- 1 small cyan cube\n- 1 small purple cylinder\n- 1 small yellow metallic ball\n- 1 small yellow shiny cylinder\n- 1 small gray matte sphere\n- 1 small gray metallic sphere\n\nSubtracting the yellow metallic ball and the two small yellow shiny cylinders:\n- Total objects: 10\n- Subtract 1 yellow metallic ball: 10 - 1 = 9\n- Subtract 2 small yellow shiny cylinders: 9 - 2 = 7\n\n</think>\n<answer>\n7.0"}]
[DEBUG] Loss: 2.632334599184105e-06
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 688.6133
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'Subtract all tiny balls. Subtract all green metallic things. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
5
Response:[{'role': 'assistant', 'content': "Subtract all tiny balls. Subtract all green metallic things. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo solve this, let's identify the objects in the image:\n\n1. There is a large yellow cube.\n2. There is a large red sphere.\n3. There is a small purple sphere.\n4. There is a small green sphere.\n5. There is a small brown sphere.\n6. There is a small gold sphere.\n7. There is a small cyan cube.\n8. There is a small gray cube.\n9. There is a large green cylinder.\n\nNow, we need to subtract all tiny balls:\n- The small purple sphere\n- The small green sphere\n- The small brown sphere\n- The small gold sphere\n\nThis leaves us with:\n- The large yellow cube\n- The large red sphere\n- The small cyan cube\n- The small gray cube\n- The large green cylinder\n\nNext, we subtract all green metallic things:\n- There is one large green cylinder, which is metallic.\n\nAfter removing the large green cylinder, we are left with:\n-"}]
[DEBUG] Loss: 1.2875904758402612e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 5128.5614
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the highest accuracy reported in the whole chart? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
8
Response:[{'role': 'assistant', 'content': 'What is the highest accuracy reported in the whole chart? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo determine the highest accuracy reported in the chart, we need to examine each dataset for all algorithms and identify the maximum value.\n\n1. For "dash":\n   - bow: ~0.5\n   - swing: ~6.0\n   - proud: ~1.0\n   - soup: ~2.0\n\n2. For "port":\n   - bow: ~7.0\n   - swing: ~6.0\n   - proud: ~5.0\n   - soup: ~7.0\n\n3. For "muzzle":\n   - bow: ~4.0\n   - swing: ~7.0\n   - proud: ~7.0\n   - soup: ~6.0\n\n4. For "want":\n   - bow: ~1.0\n   - swing: ~8.0\n   - proud: ~6.0\n   - soup: ~1.0\n\n5. For'}]
[DEBUG] Loss: 2.0394234070408856e-06
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 370.5495
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'Subtract all large red rubber blocks. Subtract all tiny red matte objects. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
2
Response:[{'role': 'assistant', 'content': "Subtract all large red rubber blocks. Subtract all tiny red matte objects. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe image contains three cubes:\n1. A large red metallic cube on the left.\n2. A small yellow cube in the middle.\n3. A small red matte cube on the right.\n\nThere are no large red rubber blocks in the image, so we don't subtract any objects for this condition.\nThere is one tiny red matte object (the small red cube on the right), which we need to subtract.\n\nAfter removing the tiny red matte object, we are left with two objects: the large red metallic cube and the small yellow cube.\n</think>\n\n<answer>\n2.0\n</answer>"}]
[DEBUG] Loss: 1.723864443192724e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 2617.7370
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the value of the largest bar? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
10000
Response:[{'role': 'assistant', 'content': 'What is the value of the largest bar? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe image is a bar chart with a logarithmic scale on the y-axis. The x-axis has categories labeled "picnic," "fair," "draw," and "candle." The y-axis ranges from \\(10^2\\) to \\(10^{10}\\).\n\n- The bar for "picnic" reaches approximately \\(10^2\\).\n- The bar for "fair" reaches approximately \\(10^4\\).\n- The bars for "draw" and "candle" are very small, close to \\(10^0\\).\n\n</think>\n\n<answer>\nThe value of the largest bar is \\(10^4\\).\n</answer>'}]
[DEBUG] Loss: 8.607935887994245e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: nan
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': '如图，AB、BC、CD、DA都是⊙O的切线，已知AD＝2，BC＝5，则AB+CD的值是（） provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
7
Response:[{'role': 'assistant', 'content': '如图，AB、BC、CD、DA都是⊙O的切线，已知AD＝2，BC＝5，则AB+CD的值是（） provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\n首先，我们知道从圆外一点到圆的两条切线长度相等。因此，在这个图形中，我们可以将AB、BC、CD、DA分别表示为两组相等的切线段。\n\n设AB = x, BC = y, CD = z, DA = w。根据题目给出的信息，我们有：\n- AD = 2，即w = 2。\n- BC = 5，即y = 5。\n\n由于AB、BC、CD、DA都是⊙O的切线，且AB、BC、CD、DA分别对应于圆上的四点A、B、C、D，我们可以得出以下关系：\n- AB + CD = AD + BC\n\n将已知数值代入上述公式：\n- x + z = 2 + 5\n- x + z = 7\n\n因此，AB + CD的值为7。\n</think>\n\n<answer>\n7.0\n</answer>'}]
[DEBUG] Loss: 9.384777513332665e-06
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 2008.3301
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
16
Response:[{'role': 'assistant', 'content': "What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe individuals in the image appear to be adults, but without specific information about their ages, it's not possible to accurately determine the exact age gap between them. The person on the left appears to be wearing traditional attire that might suggest a younger age, while the person on the right is dressed in a suit which could indicate a slightly older age. However, these are just observations based on appearance and cannot be confirmed as accurate.\n</think>\n<answer>\n(0.5)\n</answer>"}]
[DEBUG] Loss: 2.5053359422599897e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 5763.3343
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'How many algorithms have accuracy lower than 8 in at least one dataset? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
3
Response:[{'role': 'assistant', 'content': 'How many algorithms have accuracy lower than 8 in at least one dataset? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo determine how many algorithms have accuracy lower than 8 in at least one dataset, we need to examine the heights of the bars for each algorithm.\n\n1. For "cork":\n   - The bar for "crest" is below 8.\n   - The bar for "louder" is above 8.\n\n2. For "lover":\n   - The bar for "crest" is above 8.\n   - The bar for "louder" is below 8.\n\n3. For "cook":\n   - The bar for "crest" is above 8.\n   - The bar for "louder" is above 8.\n\nFrom this analysis:\n- "cork" has one algorithm with accuracy lower than 8.\n- "lover" has one algorithm with accuracy lower than 8.\n- "cook" has no algorithms with accuracy lower than 8.\n\n</think>\n\n<answer>2</answer>'}]
[DEBUG] Loss: 2.6664025426725857e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 10053.7473
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
12
Response:[{'role': 'assistant', 'content': 'What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe image shows two individuals who appear to be adults, likely in their 20s or 30s, based on their physical appearance and attire. There is no visible age gap between them; they seem to be of similar age.\n</think>\n<answer>\n0.0\n</answer>'}]
[DEBUG] Loss: 1.1813252058345824e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 1428.5617
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
3
Response:[{'role': 'assistant', 'content': 'What is the age gap between these two people in image? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe individuals in the image appear to be middle-aged adults, likely in their 50s or early 60s. The person on the left has a full beard and mustache, which can be associated with someone in their late 50s or early 60s. The person on the right also appears to be in his 50s or early 60s, given the visible signs of aging such as wrinkles and gray hair.\n\n</think>\n<answer>\nThe age gap between these two people is approximately 10 years.\n</answer>'}]
[DEBUG] Loss: 1.5990649444574956e-06
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 149.0379
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'For Group C, in which week is the cumulative increase in weight , the highest? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
3
Response:[{'role': 'assistant', 'content': 'For Group C, in which week is the cumulative increase in weight , the highest? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo determine the week when the cumulative increase in weight for Group C is the highest, we need to analyze the graph:\n\n1. Identify the line representing Group C.\n2. Observe the peak of the line.\n\nThe line for Group C (labeled "CONTROL") shows a peak at Week 4, where the cumulative increase in weight reaches its maximum value before decreasing in subsequent weeks.\n\n</think>\n<answer>\nWeek 4\n</answer>'}]
[DEBUG] Loss: 5.864560080226511e-06
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 157.1785
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': "A food industry researcher compiled the revenues of several pizzerias. How much did Dan's Deep Dish make from pizza sales? (Unit: $) provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>"}]
Answer:
22
Response:[{'role': 'assistant', 'content': "A food industry researcher compiled the revenues of several pizzerias. How much did Dan's Deep Dish make from pizza sales? (Unit: $) provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\nTo determine how much Dan's Deep Dish made from pizza sales, we need to add the revenue from pepperoni pizzas and supreme pizzas.\n\nFrom the table:\n- Dan's Deep Dish sold pepperoni pizzas for $8.\n- Dan's Deep Dish sold supreme pizzas for $14.\n\nNow, we add these amounts together:\n\n<think>\n$8 (pepperoni pizzas) + $14 (supreme pizzas) = $22\n</think>\n\n<answer>\n22.00\n</answer>"}]
[DEBUG] Loss: 4.0678452933207154e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 6575.3363
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'An author recorded how many words she wrote in the past 3 days. How many words in total did the author write on Thursday and Friday? (Unit: words) provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
679
Response:[{'role': 'assistant', 'content': "An author recorded how many words she wrote in the past 3 days. How many words in total did the author write on Thursday and Friday? (Unit: words) provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo find the total number of words written on Thursday and Friday, we need to add the number of words written on each of those days.\n\nFrom the table:\n- On Thursday, the author wrote 374 words.\n- On Friday, the author wrote 305 words.\n\nNow, let's add these numbers together:\n\n374 (Thursday) + 305 (Friday) = 679 words\n\n</think>\n<answer>\n679.0\n</answer>"}]
[DEBUG] Loss: 1.1365490536263678e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 871.2698
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What is the value of the smallest bar? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
1

Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'Use a calculator to find the measure of $∠J$ to the nearest degree. provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
40
Response:[{'role': 'assistant', 'content': 'Use a calculator to find the measure of $∠J$ to the nearest degree. provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo find the measure of ∠J in the right triangle JKL, we can use trigonometric functions. Since ∠L is a right angle, we can use the tangent function, which is defined as the ratio of the opposite side to the adjacent side.\n\nGiven:\n- The length of the hypotenuse JK = 14\n- The length of the side KL = 9\n\nWe need to find the measure of ∠J. In a right triangle, the tangent of an angle is the ratio of the length of the opposite side to the length of the adjacent side.\n\nThe formula for the tangent of ∠J is:\n\\[ \\tan(∠J) = \\frac{\\text{opposite}}{\\text{adjacent}} = \\frac{KL}{JK} = \\frac{9}{14} \\]\n\nNow, we take the arctangent (inverse tangent) of both sides to find the angle:\n\\[ ∠J ='}]
[DEBUG] Loss: 4.3012470996472985e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 796.7711
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'Subtract all big matte balls. Subtract all green rubber objects. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
7
Response:[{'role': 'assistant', 'content': "Subtract all big matte balls. Subtract all green rubber objects. How many objects are left? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe image contains the following objects:\n\n1. A large purple cube.\n2. A large gold sphere.\n3. A large teal sphere.\n4. A small red cylinder.\n5. A small green cylinder.\n6. A small green cube.\n7. A small blue metallic cube.\n8. A small teal metallic sphere.\n\nThere are no big matte balls in the image, so we don't need to subtract any objects for that condition. There are two green rubber objects: the small green cylinder and the small green cube. We need to subtract these two objects.\n\nAfter removing the two green rubber objects, the remaining objects are:\n- The large purple cube.\n- The large gold sphere.\n- The large teal sphere.\n- The small red cylinder.\n- The small blue metallic cube.\n- The small teal metallic sphere.\n\nCounting these, we have 6 objects left.\n\n</think>\n<answer>\n6.0\n</answer>"}]
[DEBUG] Loss: 0.00011047901352867484
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 9612.1438
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'What number is shown? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
7519
Response:[{'role': 'assistant', 'content': 'What number is shown? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe image shows a total of 7 large cubes, each representing 100 units (since they are likely hundreds in a base-10 system), and 5 smaller cubes, each representing 1 unit. Therefore, the total number represented is 700 + 5 = 705.\n</think>\n<answer>\n705.0\n</answer>'}]
[DEBUG] Loss: 0.0002061403647530824
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 911.5027
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'At which Episode ID does the Retroformer attain its peak Success rate (%)? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
4.0
Response:[{'role': 'assistant', 'content': 'At which Episode ID does the Retroformer attain its peak Success rate (%)? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nTo determine at which Episode ID the Retroformer attains its peak Success rate (%), we need to look at the highest point on the blue line, which represents the Retroformer.\n\n- At Episode ID 0, the success rate is approximately 35%.\n- At Episode ID 1, the success rate increases to approximately 45%.\n- At Episode ID 2, the success rate further increases to approximately 48%.\n- At Episode ID 3, the success rate reaches its peak at approximately 52%.\n- At Episode ID 4, the success rate slightly decreases to approximately 51%.\n\nThe peak success rate for the Retroformer occurs at Episode ID 3.\n</think>\n\n<answer>\n4.0\n</answer>'}]
[DEBUG] Loss: 8.606247138231993e-05
[DEBUG] Params with grad: 712 / 1441
[DEBUG] Grad norm: 207.0057
Warning: prompt_length > max_prompt_length. The prompt has been truncated, which may cause unintended behavior or a size mismatch error. Consider increasing max_prompt_length unless truncation is intentional.
test
-------------------- Question:
[{'type': 'image'}, {'type': 'text', 'text': 'Based on the image, what is the most likely equilibrium population count? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>'}]
Answer:
80
Response:[{'role': 'assistant', 'content': 'Based on the image, what is the most likely equilibrium population count? provide your reasoning between <think> and </think> and then your final answer between <answer> and (put a float here) </answer>\nassistant\n<think>\nThe graph shows a trend where the number of individuals \\( N_m \\) increases as \\( m \\) increases. However, there appears to be a plateau or saturation point after a certain value of \\( m \\). This suggests that the system has reached an equilibrium where further increases in \\( m \\) do not significantly increase \\( N_m \\).\n\nGiven the data points, it looks like the population count stabilizes around 80 individuals when \\( m \\) reaches approximately 25. This indicates that the equilibrium population count is likely close to this value.\n</think>\n\n<answer>\n80.0\n</answer>'}]

In [ ]:
model.save_pretrained("V0_GRPO")  # Local saving
tokenizer.save_pretrained("V0_GRPO")

[]